version: '3'

services:
  app:
    build: .
    container_name: glpibis-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - IP_DB=db
      - USER_DB=${MYSQL_USER:-glpiuser}
      - PASSWORD_DB=${MYSQL_PASSWORD:-glpipassword}
      - NAME_DB=${MYSQL_DATABASE:-glpidb}
    volumes:
      - ./config:/app/config
      - ./static/qr_codes:/app/static/qr_codes
    depends_on:
      - db
    networks:
      - glpibis-network

  db:
    image: mysql:8.0
    container_name: glpibis-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-glpidb}
      - MYSQL_USER=${MYSQL_USER:-glpiuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-glpipassword}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - glpibis-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: glpibis-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
    depends_on:
      - db
    networks:
      - glpibis-network

volumes:
  mysql_data:

networks:
  glpibis-network:
    driver: bridge